[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:main"

[target.i686-linux-android]
image = "ghcr.io/cross-rs/i686-linux-android:main"

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:main"

[target.armv7-linux-androideabi]
image = "ghcr.io/cross-rs/armv7-linux-androideabi:main"
